#!/bin/bash
PREFIX='/opt/checkio/forum'
shopt -s extglob

fix_virtualenv() {
	# Will run a nice tool called virtualenv_tools.py
	# This tool fixes all shebang rows in python scripts to fit new virtualenv location
	# Tool originaly taken from here: https://github.com/fireteam/virtualenv-tools
	python /usr/local/bin/virtualenv_tools.py --update-path=${PREFIX} ${PREFIX}/
}

fix_permissions() {
	chown checkio:www-data ${PREFIX}
	chown -R checkio:www-data ${PREFIX}/!(logs|remote_logs)
	chown -R checkio:logreader ${PREFIX}/*(logs|remote_logs)
	chmod o-rwx ${PREFIX}
	# Permissions required by twistd
	chmod 0751 ${PREFIX}
	chmod 0751 ${PREFIX}/lib
	chmod 0751 ${PREFIX}/lib/python2.7
}

fix_virtualenv
fix_permissions
/etc/init.d/apache2 restart

